controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_controllers:
    resource:
        path: ../src/Api/
        namespace: App\Api
    prefix: /api
    type: attribute
